#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find it on the first line, you may have the wrong interpreter.
#
#   (2) Put the shell commands in this file in double quotes, not single quotes,
#       because of variable substitution.
#
#   (3) This script is generated from the template
#       https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#       within the Gradle source tree.
#
#   You can find Gradle at https://gradle.org/
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a symlink
app_path="$0"

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}
    [ -L "$APP_HOME" ]
do
    app_path=$(readlink "$app_path")
    APP_HOME=${app_path%"${app_path##*/}"}
done

APP_HOME=$(cd "${APP_HOME:-.}" && pwd -P) || exit

app_name="$(basename "$0")"
app_script="$APP_HOME/gradlew"

if [ ! -x "$app_script" ]; then
  chmod +x "$app_script"
fi

exec "$@"
